[package]
name = "urlsafe"
version = "0.1.0"
authors = ["Chad Baxter <cbaxter@mail.umw.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"